### ISSUE TITLE
Config: friendlier handling of defaults

### ISSUE THREAD

**Issue by tuurep** [tuurep/windowlist#15]
Currently the program breaks if you remove any key in `config.toml`. Would be nicer if it would just fallback to the default value in that case. This way users who only want to change a few keys can have a `config.toml` of only a few lines.

Should be simple, for each key just check:

```
if (!tbl.key) {
    config.key = <default>
} else {
    config.key = tbl.key
}
```

**Comment by tuurep** [comment]
Now it's possible to remove the keys where you want to use the defaults. For example, here's my own `config.toml` going forward:

```toml
sort_by = "position"
separator_string = "󰧟"

[window_nicknames]
TelegramDesktop = "telegram"
```
