### ISSUE TITLE
Add defaults to the README table

### ISSUE THREAD

**Issue by tuurep** [tuurep/windowlist#26]
https://github.com/tuurep/windowlist/discussions/25

Request by @Dupond

> I'd have appreciated being able to know what the default configuration options were without having to open the `config.toml` file; perhaps it would be possible, in the [configuration table](https://github.com/tuurep/windowlist#configuration), to add " (default)" in each line next to the default value?

Yes let's add these.

**Comment by tuurep** [comment]
Otherwise I'd just go for it, but there are these rows:

![Image](https://github.com/user-attachments/assets/dbf8fa5a-2672-469e-889f-401d60350206)

With these defaults:

```toml
active_window_left_click   = "minimize"
active_window_middle_click = "none"
active_window_right_click  = "close"
active_window_scroll_up    = "none"
active_window_scroll_down  = "none"

inactive_window_left_click   = "raise"
inactive_window_middle_click = "none"
inactive_window_right_click  = "close"
inactive_window_scroll_up    = "none"
inactive_window_scroll_down  = "none"
```

Maybe separate click actions to 4 rows like:
```
left click inactive         | default: "raise"
----------------------------|---------------------
left click active           | default: "minimize"
----------------------------|---------------------
right click active          | default: "close"
right click inactive        |
----------------------------|----------------------
('the extra mouse actions') | default: "none"
<all the rest here>         |
```
Something like that

Colors are all "none" except `inactive_window_fg_color` and `separator_fg_color`

"none" for `fg` and "none" for `bg`/`ul` kind of don't mean the same thing:
- `fg` "none": use default polybar fg color
- `bg`/`ul` "none": don't use bg/ul color (i.e. it's *off*)

Oh yes this is already in the table.

But gotta figure out how to be clear about the defaults.

Maybe what I should try to do is try to split all keys on their own table row, then see which parts have too much repetition, and then group those rows again.
