### ISSUE TITLE
New click actions missing: double click (left, middle, right)

### ISSUE THREAD

**Issue by tuurep** [tuurep/windowlist#33]
Just noticed there are new click actions I never knew about:

https://github.com/polybar/polybar/wiki/Formatting#action-a

> - `6`: double left click
> - `7`: double middle click
> - `8`: double right click
>
> **Note**: Double click actions are only triggered if they occur within the `double-click-interval` specified in the [bar section](https://github.com/polybar/polybar/wiki/Configuration#bar-settings).

Definitely add options for these,
Defaults: no action
Mention `double-click-interval` in the table description.

**Comment by tuurep** [comment]
Usage:

`click-actions/fooficate`:

```bash
#!/bin/bash

notify-send "a" "a"
```

`$ chmod +x fooficate`

`config.toml`:

```toml
active_window_left_double_click     = "fooficate"
active_window_right_double_click    = "fooficate"
active_window_middle_double_click   = "fooficate"
inactive_window_left_double_click   = "fooficate"
inactive_window_right_double_click  = "fooficate"
inactive_window_middle_double_click = "fooficate"
```

`config.ini` option `double-click-interval` under the `bar` section determines (in milliseconds) when a click is considered single-click.

I believe the default is 400ms (awfully long in my opinion, but nobody asked)

Important: When the double click actions are "none" in `config.toml`, there is *no* delay for single-click actions, regardless of what `double-click-interval` is set as.
